CREATE TABLE IF NOT EXISTS Users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(4000) NOT NULL,
    status INT NOT NULL DEFAULT (1)
);

CREATE TABLE IF NOT EXISTS Roles (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS UserRoles (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (`user_id`, `role_id`),
    CONSTRAINT `FK_UserRoles_User` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT `FK_UserRoles_Roles` FOREIGN KEY (`role_id`) REFERENCES `Roles` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS Categories (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TaskItems (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    category_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    priority INT NOT NULL,
    completed BIT NOT NULL DEFAULT (0),
    created_at DATETIME NOT NULL DEFAULT NOW(),
    completed_at DATETIME NULL,
    CONSTRAINT `FK_TaskItems_User` FOREIGN KEY (`user_id`) REFERENCES `Users` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT `FK_TaskItems_Category` FOREIGN KEY (`category_id`) REFERENCES `Categories` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
);