services:
  api:
    build:
      context: .
      dockerfile: src/TaskManagementSystem.WebApi/Dockerfile.dockerfile
    ports:
      - "${API_PORT}:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      TskMgr_DatabaseProvider: ${TskMgr_DatabaseProvider}
      TskMgr_ConnectionStrings__MariaDbConnection: ${TskMgr_ConnectionStrings__MariaDbConnection}
      TskMgr_Jwt__Issuer: ${TskMgr_Jwt__Issuer}
      TskMgr_Jwt__Audience: ${TskMgr_Jwt__Audience}
      TskMgr_Jwt__SecretKey: ${TskMgr_Jwt__SecretKey}
    depends_on:
      - db

  db:
    image: mariadb:11.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_taskmanager_data:/var/lib/mysql

  migration-tool:
    image: flyway/flyway:11
    command: -url=jdbc:mysql://db/${MYSQL_DATABASE} -user=root -password=${MYSQL_ROOT_PASSWORD} -locations=filesystem:/flyway/migrations -connectRetries=30 migrate
    volumes:
      - ./db/${TskMgr_DatabaseProvider}:/flyway/migrations
    depends_on:
      - db

volumes:
  mariadb_taskmanager_data: